### ISSUE TITLE
Highlighting breaks with Helix editor

### ISSUE THREAD

**Issue by tynanbe** [gleam-lang/tree-sitter-gleam#79]
It looks like it stopped working at this commit: https://github.com/gleam-lang/tree-sitter-gleam/commit/b7ae2c9374083e4f4569a2f9e218efe409f98664

**Comment by the-mikedavis** [comment]
Do you have custom config in `~/.config/helix/languages.toml` to update the `[[grammar]]` block? Generally you can't update the parser alone - if there are breaking changes like in https://github.com/gleam-lang/tree-sitter-gleam/commit/23d2b896514087d97f75a62035b325a4704cbae5 (the parent of the commit you linked) then the queries might fail to compile.

Also see https://github.com/helix-editor/helix/pull/9003 - that PR has the updates for the queries that should fix query compilation.

**Comment by tynanbe** [comment]
Using Helix v23.10, with this in `languages.toml`:

```toml
[[grammar]]
name = "gleam"

[grammar.source]
git = "https://github.com/gleam-lang/tree-sitter-gleam"
rev = "23d2b896514087d97f75a62035b325a4704cbae5"
```

I do see an error in `helix.log` stating that the Gleam queries couldn't be parsed, after running the following with any rev newer than the above.

```sh
> hx --grammar fetch && hx --grammar build
```

Sounds like I need a newer Helix build?
